#!/bin/sh

cmd="$(dmenu_path |
  dmenu -p '$' -l 10 -fn 'Liberation Sans-12:Bold' -nb '#000000' -nf '#ffffff')" ||
    exit

if output="$(${SHELL:-"/bin/sh"} -c "$cmd" 2>&1)" ; then
  urgency=normal
  icon=emblem-default
else
  urgency=critical
  icon=emblem-important
fi

if [ -z "$output" ]; then
  notify-send --icon="$icon" --urgency="$urgency" "$cmd"
else
  notify-send --icon="$icon" --urgency="$urgency" "$cmd" "$output"
fi

ret=$?
[ $ret -eq 0 ] || {
  echo "Failed to direct '$cmd' output through notify-send."
  [ -z "$output" ] || echo "$output"
} >&2
exit $ret
